import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import ReduxProvider from "@/redux/ReduxProvider";
import TopMenu from "@/components/TopMenu";

import { Nunito } from "next/font/google";
import Footer from "@/components/Footer";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "700"], 
  variable: "--font-nunito", 
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className={nunito.variable}>
      <body className="font-sans">
        <ReduxProvider>
          <NextAuthProvider session={session}>
            <TopMenu/>
            {children}
            <Footer/>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
